name: recam_flutter
description: ReCam - AI powered analog camera.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- UI 图标库 ---
  cupertino_icons: ^1.0.8

  # --- 你的核心 Swift 插件 (本地路径) ---
  recam_native_camera:
    path: recam_native_camera

  # --- 本地存储 (记账本 & 配置) ---
  shared_preferences: ^2.2.2

  # --- 时间格式化 ---
  intl: ^0.19.0

  # --- 权限管理专家 ---
  permission_handler: ^11.0.1

  # --- 外部跳转 ---
  url_launcher: ^6.2.4

  # --- 获取 App 版本号 ---
  package_info_plus: ^5.0.1

  # --- 备用相机库 ---
  camera: ^0.10.5

  # ✅ [本次新增] 截图库 (用于保存编辑后的图片)
  screenshot: ^3.0.0

  # ✅ [本次新增] 路径库 (用于获取临时文件目录)
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true